services:
  assistant:
    image: ${ai_assistant_production}
    volumes:
      - .:/AI-Assistant:rw
      - static:/static
    ports:
      - "${FLASK_HOST_PORT}:${FLASK_INTERNAL_PORT}"
    command: >
      sh -c "
      gunicorn -w 4 --bind 0.0.0.0:${FLASK_INTERNAL_PORT} --timeout 180 --log-level debug run:app
      "
    restart: always
    depends_on:
      - qdrant
      - redis
      - mongodb
    environment:
      - .env

  qdrant:
    image: qdrant/qdrant:latest
    ports: 
      - "${QDRANT_HOST_PORT}:${QDRANT_INTERNAL_PORT}"
      - "${QDRANT_GRPC_HOST_PORT}:${QDRANT_GRPC_INTERNAL_PORT}"
     

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_INTERNAL_PORT}"
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "${MONGODB_HOST_PORT}:${MONGODB_INTERNAL_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db

volumes:
  vectordata:
  mongodb_data:
  static: 
