# Local_Deployment

# deploy_custom_atomspace
- name: Custom Atomspace builder_Local
  hosts: Custom_Atomspace_builder_Local
  tags: Custom_Atomspace_builder_Local
  become: true
  roles:
    - Custom_Atomspace_builder
  
  # deploy_annotation
- name: Deploy Annotation Service
  hosts: annotation_Local
  tags: annotation_Local
  become: true
  roles:
    - Annotation

  # deploy_MORK
- name: Deploy MORK Service
  hosts: MORK_Local
  tags: MORK_Local
  become: true
  roles:
    - MORK

# deploy_UI
- name: Deploy UI Service
  hosts: UI_Local
  tags: UI_Local
  become: true
  roles:
    - UI

#Remote_Deployment

# deploy_UI
- name: Deploy UI Service
  hosts: UI_Remote
  tags: UI_Remote
  become: true
  roles:
    - UI
# deploy_custom_atomspace 
- name: Custom Atomspace builder_Remote
  hosts: Custom_Atomspace_builder_Remote
  tags: Custom_Atomspace_builder_Remote
  become: true
  roles:
    - Custom_Atomspace_builder
  
  # deploy_annotation 
- name: Deploy Annotation Service
  hosts: annotation_Remote
  tags: annotation_Remote
  become: true
  roles:
    - Annotation

  # deploy_MORK
- name: Deploy MORK Service
  hosts: MORK_Remote
  tags: MORK_Remote
  become: true
  roles:
    - MORK

# Setup shared Docker network for all local services
- name: make the same network for all docker services
  hosts: local_network
  tags: local_network
  become: true
  roles:
    - network
